### ISSUE TITLE
Data Streaming and Loggregator

### ISSUE THREAD

**Issue by jerodsanto** [GoTimeFM/ping#10]
Carlisia once requested we do a Changelog episode on data streaming. Context:

https://github.com/thechangelog/ping/issues/310

After multiple false starts getting that show scheduled, I think it actually makes more sense as a Go Time episode than a Changelog episode.

@bridgetkromhout (mentioned not that issue) says that @kicombs is the best person to come on if the main topic is Loggregator.

Looking forward to seeing what comes of this! :beers:

**Comment by jadekler** [comment]
I'm sure loggregator members @jasonkeene and @nelsam would be interested too.

**Comment by jasonkeene** [comment]
I would be interested in discussing data streaming in Go. I can get a few of our team members to participate as well.

**Comment by carlisia** [comment]
@jasonkeene we are working out our queue, this is an interesting topic for the show, just hang on! :)

**Comment by jerodsanto** [comment]
It happened! It really happened! 😉

https://changelog.com/gotime/61

I'm happy to finally see this show exist 💚
