### ISSUE TITLE
Show - Imposter Syndrome

### ISSUE THREAD

**Issue by SharonAllsup** [GoTimeFM/ping#12]
_(some comments from the #gotimefm channel)_

Scott Mansfield [8:58 PM]  
it'd be interesting to talk about impostor syndrome on the show

Erik St. Martin [9:00 PM]  
Yeah, I'd love to have an episode on that. Let a few people speak from the heart about how they view themselves

https://gophers.slack.com/archives/gotimefm/p1470272414000858

_(more of that conversation, below, for context)_

Scott Mansfield [8:00 PM]  
everyone has impostor syndrome

[8:02]  
it's actually very common, people just don't talk about it

Sharon Allsup [8:02 PM]  
Yep.  Everyone that I know who'll admit it, does

[8:04]  
I've been midway through a presentation on a system I designed, wrote most of, supported for years, knew in my ​_bones_​, represented it at all levels of IT project handling, was the uncontested SME for ... and ​_still_​ felt halfway through this talk to new support staff that I was just faking it.  That's when you have to have a good talking-to with the self-esteem - "Get real, OK?"

Erik St. Martin [8:25 PM]  
Everyone has impostor syndrome. With the internet we are too connected and comparing ourselves with the rest of the world.

[8:27]  
Ask Brian, I'm always super critical of my own skills and abilities. I don't like public speaking or blogging for fear that I'll be wrong or not to the caliber people expect out of me

[8:29]  
I highly agree with @sgmansfield on the people are people aspect. Putting people on a pedestal and treating them as Titans doesn't help your own impostor syndrome because it puts you further away, and it doesn't help their impostor syndrome either because secretly it makes them feel even more like a fraud because of the status they feel is unwarranted

[8:30]  
At the end of the day, we are all people, engineers trying to perfect our craft

[8:31]  
We are all on the same journey, just may have taken separate paths

_(a bit later in the convo, and what led to this post) -_ 

Scott Mansfield [8:58 PM]  
it'd be interesting to talk about impostor syndrome on the show

Erik St. Martin [9:00 PM]  
Yeah, I'd love to have an episode on that. Let a few people speak from the heart about how they view themselves

Scott Mansfield [9:01 PM]  
looks like @chaseadamsio just volunteered :troll:

Erik St. Martin [9:01 PM]  
I'm fortunate to get to have behind the scenes conversations with a lot of people we all view as big names, who have the same feelings as the rest of us. That the work they perform isn't as amazing as others perceive it to be, that it's just micro iterations on the same thing(s) they've been working on their whole career

[9:02]  
The equivalent of losing weight. You're too close to the problem to see the gains, only the outside world notices the change (edited)

**Comment by chaseadamsio** [comment]
I gave it a 👍 , but the 👍 doesn't really do justice how important I think this topic is. Thanks for adding it to the issues @SharonAllsup!

**Comment by arschles** [comment]
Another 👍 here. This topic _needs_ to be talked about more

**Comment by jerodsanto** [comment]
We're covering this topic live in about 43 minutes! Join #gotimefm in gophers slack if you want to participate 👍

**Comment by jerodsanto** [comment]
This show went live awhile back and I forgot to close the issue 🤦‍♂️ 

https://changelog.com/gotime/30

Hope y'all enjoyed it as much as we did! 🍻
