### ISSUE TITLE
Talk to Steve Francia about his new role with the Go language team

### ISSUE THREAD

**Issue by jerodsanto** [GoTimeFM/ping#13]
[Hugo](https://gohugo.io) is awesome. [Steve](https://twitter.com/spf13) is awesome. I'd love to hear a show featuring them!

**Comment by carlisia** [comment]
Trying to schedule this with Steve, but it will probably lean more towards his new role with the Go language team.

**Comment by jerodsanto** [comment]
Done and dusted https://changelog.com/gotime/38
