### ISSUE TITLE
A show about Noms

### ISSUE THREAD

**Issue by jerodsanto** [GoTimeFM/ping#14]
[Noms](https://github.com/attic-labs/noms) is a really interesting new database that draws many ideas from Git. The source code is 64% Go and 37% JavaScript, so I suspect that @bketelsen will 64% _love_ and 37% _despise_ a conversation about it. 😜 

I, for one, would _love_ the entire show. Y'all should book it before I do it for The Changelog. :smile:

**Comment by carlisia** [comment]
Issue #16 is a suggestion for the same topic, so I'm gonna close this @jerodsanto. 👍
