### ISSUE TITLE
Talk to the creator of Go In 5 Minutes (me) about design patterns

### ISSUE THREAD

**Issue by arschles** [GoTimeFM/ping#18]
Hey all - creator of [Go In 5 Minutes](https://goin5minutes.com) here. I'd like to come on the show and talk about the screencasts. Specifically: why I started it, for whom I started it, and what keeps me motivated.

I can also touch on some of the biggest design patterns I've covered, and some I'm gonna cover soon.

**Comment by carlisia** [comment]
Closing, this has been scheduled!
