### ISSUE TITLE
iTunes

### ISSUE THREAD

**Issue by vort3x** [GoTimeFM/ping#2]
Would be nice if you can add your podcast into iTunes.

**Comment by carlisia** [comment]
Hey @vort3x we will! The approval process takes a while, and we are getting thing lined up for that. Thanks for listening!

**Comment by adamstac** [comment]
The show is now in iTunes -> https://itunes.apple.com/us/podcast/go-time/id1120964487?mt=2

If you’ve listened to the show, login to iTunes and rate the show pls.
