### ISSUE TITLE
[Mention] Better Go Playground Chrome extension

### ISSUE THREAD

**Issue by dlsniper** [GoTimeFM/ping#20]
I think this should be mentioned in one of the shows: https://chrome.google.com/webstore/detail/better-go-playground/odfhkelcmblecfdnboahphiafolojmpl

It makes lovely things like this: 
![snapshot138](https://cloud.githubusercontent.com/assets/607868/18731371/6e002880-8053-11e6-905b-6c6b2333865e.png)

**Comment by carlisia** [comment]
This is so cool, I love it. Thanks for the mention @dlsniper! Marked for mention, closing. 👍
