### ISSUE TITLE
[Free Software Friday] Have I been Pwned?

### ISSUE THREAD

**Issue by dlsniper** [GoTimeFM/ping#21]
It's not really Go related but I find this to be invaluable, https://haveibeenpwned.com/
The notification whenever there's a breach that comes public is <3

**Comment by carlisia** [comment]
@dlsniper is this open source?

**Comment by dlsniper** [comment]
No, it's not but considering it's free and useful I thought maybe it will work out. Up to the hosts to shout it or not. Thank you!

**Comment by carlisia** [comment]
Ah the free software friday spot is for free software as in open source (as in freedom). Let's find a different way to promote them. Closing this issue.
