### ISSUE TITLE
guest: Todd McLeod

### ISSUE THREAD

**Issue by GoesToEleven** [GoTimeFM/ping#22]
I would love to contribute to the podcast by being a guest. 

I've been coding in Go since 2014. I've taught 7 university and college sections of web dev with Go, including grad students in comp sci. I organized and ran a 10-week summer web bootcamp in 2015 where, for four weeks, eight hours a day, 5 days a week, Caleb Doxsey taught web dev with Go. I have trained over 41,000 students in the Go programming language on Udemy. I have taught a gobridge weekend workshop. I am building a community based learning platform all in Go. And I am also the lynda.com author for the Go "code clinic" series where I present solutions to challenges like turning the mouse into a musical instrument and finding images extracted from other images by using a sum of absolute differences. 

I think I have an interesting story as a programmer, and as a Go programmer, which would be helpful to others - the most interesting point: my formal educational background is economics and business, and I just started learning programming in 2013. 

Sometimes I am blown away by how much has happened in just 3 years. 3 years ago I didn't know the difference between an array or a map or an object or an interface or a class or a struct. 

My ultimate goal for presenting would be to offerer inspiration, encouragement, and resources for those learning, or wanting to learn, programming with Go. 

If there is one phrase I would want to leave with people it would be, "You can do it."

I would love to share my journey, talk about Go, inspire others, and have some laughs.

Let me know if this sounds good!

**Comment by caseyw** [comment]
I'd like to see this fella on the show. I think a lot of people have gotten started from his videos.

Thanks for what you're doing Todd.

**Comment by MAHDTech** [comment]
+1 from me, Todd got me started on Go, his training has been great!

**Comment by carlisia** [comment]
@GoesToEleven is going to be on tomorrow y'all.

**Comment by jerodsanto** [comment]
This episode is live!

https://changelog.com/gotime/26
