### ISSUE TITLE
Suggestion for guest and topic Peter Bourgon 

### ISSUE THREAD

**Issue by maleck13** [GoTimeFM/ping#23]
I would love to hear more of what Peter Bourgon has to say about Golang and software development in general.
I listened to his talk at golang uk  https://www.youtube.com/watch?v=JXEjAwNWays and thought it was excellent. His go kit library also seems excellent, although I haven't used it directly and his blog posts on best practices was excellent too https://peter.bourgon.org/go-best-practices-2016/

**Comment by nathany** [comment]
That would be cool. @peterbourgon is also working with the package management committee.

Meanwhile, he was on Changelog a while back. https://changelog.com/podcast/163

**Comment by adamstac** [comment]
Thanks for linking up The Changelog @nathany for those wanting to hear from him in the meantime. We also got him on camera at GopherCon 2015 — https://changelog.com/films/gophercon-2015

**Comment by peterbourgon** [comment]
Hey! I've got a face for radio, you should prefer the podcast to the video :) Happy to chat on Go Time in the future. My schedule is pretty wacky for the next weeks, but we can figure something out I'm sure. Ping me on Slack or somewhere?

**Comment by adamstac** [comment]
Oh, check out Peter here too https://beyondcode.tv/peter-bourgon/

@peterbourgon we'll get an email to you with some dates to choose from.

**Comment by carlisia** [comment]
Done!
