### ISSUE TITLE
Building a community (Meetups, GoBridge events, etc)

### ISSUE THREAD

**Issue by webRat** [GoTimeFM/ping#26]
I'd like to raise awareness of @corylanou's Go-Meetup repo - https://github.com/corylanou/go-meetup. I recently started up @FraminghamGo using this resource, along with some other connections. 

I'd like to also suggest bringing @corylanou back on, and maybe add @briandowns (who recently started up Phoenix Go Meetup). Perhaps @jboursiquot who started up Boston Go and then recently relocated to Baltimore, starting up Baltimore Go.

**Comment by corylanou** [comment]
I'm more than happy to come on, but I really would love to hear from other meetup organizers.  They deserver some recognition for all they do.  It would also be great to have that type of round table to share ideas and see what has worked and what hasn't, what tends to still be the biggest challenges to overcome.  Things they didn't expect to happen but did (good and bad).

It would be awesome to come out of this as well for additions/changes to that repo to continue to support the community.

**Comment by briandowns** [comment]
Thanks @webRat for the mention and @corylanou for the additional thoughts on this. I'd be happy to participate, and especially so in the way described above.
