### ISSUE TITLE
Matt Farina

### ISSUE THREAD

**Issue by mattfarina** [GoTimeFM/ping#3]
Being a former podcaster I'm always looking to help along podcasts on topics I like. If you're looking for folks I could come and talk about package management, [glide](https://glide.sh), [Go in Practice](https://www.manning.com/books/go-in-practice), and about Go use at [HPE](https://www.hpe.com).

**Comment by carlisia** [comment]
Hi @mattfarina, thanks for getting in touch. We’re working on the show schedule, and we’ll get in touch when we’re ready to get you on the schedule.

**Comment by carlisia** [comment]
Hang in there @mattfarina, we shall get back to you post-gophercon.

**Comment by erikstmartin** [comment]
Hi @mattfarina please email me estmartin@gopheracademy.com and i'll get you on the schedule.

**Comment by jerodsanto** [comment]
Closing for cleanliness. 💚
