### ISSUE TITLE
Paul Dix as Guest Speaker

### ISSUE THREAD

**Issue by corylanou** [GoTimeFM/ping#30]
Paul Dix has been in the Go community for quite a while.  He's also created a pretty amazing vision for the entire metrics problem of time series data.  I think it would be great to see him on Go Time, and find out why he chose Go, how Go continues to allow Influx to solve the entire full stack problem of time series data, and talk about the crazy cat shirt he wears from time to time.

/cc @pauldix

**Comment by carlisia** [comment]
Thanks for the suggestion @corylanou! You can listen to the show here: https://changelog.com/gotime/64
