### ISSUE TITLE
Dominik Honnef

### ISSUE THREAD

**Issue by ScottMansfield** [GoTimeFM/ping#34]
Creator of many go tools that people rely on on a daily basis. I've heard firsthand about many interesting technical problems in the code tools space. Seems like he could enlighten the audience on the difficulties of writing quality source code tooling.

**Comment by ScottMansfield** [comment]
not to mention the hair
![dominikh_with_hair](https://cloud.githubusercontent.com/assets/184105/25309498/fa344c5a-2783-11e7-8168-8725ccd29441.jpeg)

**Comment by DocMerlin** [comment]
I agree, you guys should interview Dominik, his tools are great!

**Comment by StabbyCutyou** [comment]
As a fellow individual with beautiful hair, I endorse this idea.

Good tools, great hair.

**Comment by jerodsanto** [comment]
Sorry friends. We tried, but Dominik isn't up for the task. Keep the great suggestions coming! 💚
