### ISSUE TITLE
Email Address? Comment Section?

### ISSUE THREAD

**Issue by tomihasa** [GoTimeFM/ping#35]
With podcasts I'm used to email addresses where I can give feedback or ask questions. Do you have an email address for your podcast? Do you have a comment section for your podcast episodes? I don't like Slack or any other chat/messenger as they take my ability to concentrate, so I don't use any. I have disabled all notifications in my operating systems, browsers, etc.

**Comment by tomihasa** [comment]
Related to giving feedback: some podcasts have their own Reddit page where users can give advice on news stories. Maybe create one if you haven't already?

**Comment by jerodsanto** [comment]
@tomihasa thanks for listening to the show! This is the the right spot for show feedback, suggestions, etc.

If you'd like to provide private feedback, you can also email editors@changelog.com 💚

**Comment by tomihasa** [comment]
Cool!
