### ISSUE TITLE
GoTime on Spotify?

### ISSUE THREAD

**Issue by yashrajsingh** [GoTimeFM/ping#40]
Spotify recently added support for podcasts, is GoTime planning to join? Any thoughts.

**Comment by jerodsanto** [comment]
We'd love to be in Spotify! Unfortunately, they don't accept open submissions at the moment, so we can't just submit the show there and expect anything to come of it.

If you know anybody who works there and could help us out, we'd love an intro 😁

**Comment by leitzler** [comment]
Have you tried filing [https://docs.google.com/forms/d/e/1FAIpQLSfKJ76t_tPV2jugdX14NeajSfp7EV0hcgjVki1GEGuoeyJvDw/viewform?c=0&w=1](url)?

**Comment by jerodsanto** [comment]
@leitzler we have now! Thanks for the link 👍

**Comment by adamstac** [comment]
Closing for now. We're following up with them.
