### ISSUE TITLE
Speaker suggestion: Michael Stapelberg

### ISSUE THREAD

**Issue by Merovius** [GoTimeFM/ping#41]
As we talked about at Gophercon, you might want to invite @stapelberg (author of i3 as well as a bunch of go projects like gokrazy, RobustIRC, Debian codesearch,…) on the show :) You can also reach him on [twitter](https://twitter.com/zekjur).

**Comment by bketelsen** [comment]
Good god yes.  Tried to reach out on twitter but @stapelberg doesn't follow me, send public reply instead.

**Comment by erikstmartin** [comment]
Michael has been scheduled and recorded. Closing
