### ISSUE TITLE
Ivan Porto Carrero as a Guest Speaker 

### ISSUE THREAD

**Issue by kars7e** [GoTimeFM/ping#42]
I would love to hear @casualjim on the show. For those who don't know Ivan, he's the man behind go-swagger (https://github.com/go-swagger/go-swagger): Great, complete implementation of swagger 2.0 that makes working with REST API in Go super easy. Go-swagger is used by many super well-known projects out there: Kubernetes, Docker, openshift and many others.

Ivan is also the author of Scalatra (https://github.com/scalatra/scalatra) - a tiny framework written In Scala, based on Ruby's Sinatra. It would be great to hear his thoughts on Go and why transitioned from Scala to Go.

**Comment by erikstmartin** [comment]
We'd love to have Ivan on the show. Do you have a means of contacting him. Please shoot me an email at estmartin@gopheracademy.com with contact details or have Ivan reach out via email or twitter and we'll get him on the schedule.

**Comment by jerodsanto** [comment]
Consider it 🚢'd!

https://changelog.com/gotime/60

Thanks for the suggestion @kars7e, hope you enjoy the show! 💚
