### ISSUE TITLE
Add github link to https://changelog.com/gotime

### ISSUE THREAD

**Issue by Zanadar** [GoTimeFM/ping#46]
I went to the gotime site on `changelog.com` because Brian(?) I think mentioned something about issue and contributing to transcripts, but I could find the github repo without some digging.  I wonder if that could be linked directly on the gotime homepage to make the repo more discoverable.

**Comment by jerodsanto** [comment]
Good idea. I squeezed it in here:

<img width="679" alt="2017-12-15 at 9 37 am" src="https://user-images.githubusercontent.com/8212/34049066-a365bbea-e17b-11e7-91e4-ceebf84fe210.png">

Hopefully that's sufficient. ✊
