### ISSUE TITLE
Add https://blog.aqwari.net/9p/ to the show notes for EP 62

### ISSUE THREAD

**Issue by Zanadar** [GoTimeFM/ping#47]

**Comment by jerodsanto** [comment]
👋 @Zanadar! Would you please provide some context for adding this to the show notes? Thanks!

**Comment by Zanadar** [comment]
Apologies...that would have been helpful!

At one point (around https://changelog.com/gotime/62#t=00:51:34.09) Jeff and Brian are discussing the 9P protocol, and Brian mentions that the article was linked in some hacker new article about the protocol and that he tweeted it out.  

I ended up looking through slack and found it, but it would have been cool to be able to find it directly in the notes.

P.S. Its awesome you have this, and thanks for everything you do!

P.P.S. The timeline links for the transcript are great!  (I do wonder how simple it would be to make them work, ala github line numbers, for the individual blocks or paragraphs of conversations in order to provide more granular links to transcript).

**Comment by jerodsanto** [comment]
> Apologies...that would have been helpful!

No worries. 😄

> I ended up looking through slack and found it, but it would have been cool to be able to find it directly in the notes.

It's there now. ✊

P.S. You're welcome! Thanks for being part of our awesome community.

P.P.S. You have no idea how much I want this! Unfortunately, it is not _simple_ at the moment, but I've found [a tool](https://github.com/lowerquality/gentle) to help us get word-for-word timestamp data, so it is definitely possible. It's on the long-term todo list, but not highest priority at the moment.
