### ISSUE TITLE
Jon Calhoun as guest speaker

### ISSUE THREAD

**Issue by fteem** [GoTimeFM/ping#48]
- Book author: [Web Development in Go](https://www.usegolang.com/)
- Teacher: [Gophercises](gophercises.com) 🚀 
- Blogger: [calhoun.io](calhoun.io)

I think @joncalhoun does a really good job with Gophercises and the community should get to know more about him and his projects!

**Comment by joncalhoun** [comment]
Thanks @fteem - this is very flattering! Are there any specific topics you'd like to hear about?

I'm open to the idea, but I have no experience speaking on a podcast and don't know the GoTimeFM audience well enough to know what they would find interesting.

**Comment by fteem** [comment]
@joncalhoun 👋  I think you are doing a really nice job with Gophercises, although still early in the game. I think that you have a nice delivery, the content is cool, well organised, detailed and very hands on. Coming from Ruby land, it really reminds me of [Railscasts](http://railscasts.com/) and how monumental it was for the Ruby community over the years.

> Are there any specific topics you'd like to hear about?

I cannot think of a good one at this moment. Probably about the idea behind Gophercises, coming up with content (inspiration), writing your book (that, frankly, I haven't read yet), etc.

> ... I have no experience speaking on a podcast ...

I think that shouldn't be a problem 😉

**Comment by jerodsanto** [comment]
This show is scheduled! 🎉
