### ISSUE TITLE
Guest suggestion: Edward Muller

### ISSUE THREAD

**Issue by davecheney** [GoTimeFM/ping#7]
Edward Muller recently started a survey of Go programmers. He's going to do a lightning talk about it at gophercon, but seven minutes won't do the subject justice. How about having Edward on the show?

**Comment by carlisia** [comment]
Ok @davecheney, we knew you were going to make this request, and because we love you we proactively booked Ed already and got all the things done! Ed was the recording we did last week! It was episode #10. We talked about Go at Heroku and also about his survey.

**Comment by davecheney** [comment]
Lol. Close this as "working as intended"

**Comment by carlisia** [comment]
LOL
