### ISSUE TITLE
Guest suggestion: the go compiler team

### ISSUE THREAD

**Issue by davecheney** [GoTimeFM/ping#8]
The Go compiler team delivered a new SSA based back end for go 1.7. At the moment this is amd64 only, but the development branch now also includes support for 32 bit arm.

The plan for go 1.8 is to convert the remaining back ends to SSA,and dump the old backedx which have been ported from the plan 9 compilers of the 90's

How about have one or more of the people who contributed to the dev.ssa branch on the show?

**Comment by carlisia** [comment]
I love it. Do you think you could help us contact one of the members? For technical reasons we should only have 1 guest at a time.

**Comment by davecheney** [comment]
Let's button hole one of them at Gophercon. David Chase would be an
excellent choice.

**Comment by carlisia** [comment]
Awesome. I'm confident that @erikstmartin and @bketelsen will agree that it will be good to have someone with that level of knowledge talk compiler geekery on the show. Thanks for helping us with this!

**Comment by carlisia** [comment]
Hey @davecheney, @bketelsen, did you guys have a chance to talk to David Chase about this?

**Comment by davecheney** [comment]
Nope, I didn't realise it was on me to make the intro.

**Comment by StabbyCutyou** [comment]
David is my point of contact for the Boston go meetups that Google now graciously hosts.

Would you like me to send him a note about this?

**Comment by carlisia** [comment]
Hey @StabbyCutyou that woud be great, thank you!

**Comment by StabbyCutyou** [comment]
My pleasure.

I'll reach out and let you know.

**Comment by StabbyCutyou** [comment]
I spoke with David.

His biggest concern is that he is pretty busy overall, but I told him that you all typically set these up well in advance so that you could accommodate his schedule (I don't think that was too much of a fib).

I linked him to this thread so he could chime in if we had time.

Best of luck!

**Comment by dr2chase** [comment]
Hi, I got contacted, what would you like to talk about?

**Comment by carlisia** [comment]
Hi @dr2chase! Compiler! But really, anything that you would like to talk about and think would be interesting to the community. 

We might have this Thursday open, if not, May 11th is available. The show records every Thursday at 11:45AM PST and goes for about 1:30hr.

Let me know if you can join us!

**Comment by dr2chase** [comment]
May 11 is probably better.  So, 2:45pm Eastern time, till about 4:15?  How do we connect?

**Comment by erikstmartin** [comment]
Excellent, I'll put you on the calendar for May 11th. Really looking forward to this. On your end you'll just need access to skype and a pair of headphones.

**Comment by jerodsanto** [comment]
@dr2chase also check out this setup guide to prep for the show. Let us know if you have any questions.

https://changelog.com/guest/gotime

We're looking forward to it!
